using System;
using System.Collections.Generic;
using System.Numerics;
using System.Text;
using System.Linq;
using System.Diagnostics;

using _calc = MathService.Calculators.Calculator;

namespace ProblemService.Problems
{
    public class Problem_45 : Problem
    {
        //https://projecteuler.net/problem=45 Published on Friday, 6th June 2003, 05:00 pm; Solved by 61407;    Difficulty rating: 5%
        //                                      
        // Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
        //
        // Triangle     Tn = n(n + 1) / 2	 	1, 3, 6, 10, 15, ...
        // Pentagonal   Pn = n(3n−1) / 2	 	1, 5, 12, 22, 35, ...
        // Hexagonal    Hn = n(2n−1)	 	    1, 6, 15, 28, 45, ...
        //
        // It can be verified that T285 = P165 = H143 = 40755.
        //
        // Find the next triangle number that is also pentagonal and hexagonal.

        public override object RunProblem(double x, double y = 0, double z = 0)
        {
            var max = (int)x;

            var tris = new SortedSet<long>();
            var pents = new SortedSet<long>();
            var hexs = new SortedSet<long>();

            for (long i = 1; i <= max; i++)
                tris.Add((i * i + i) / 2);

            for(long i = 1; i <= max; i++)
            {
                var p = (3 * i * i - i) / 2;
                if (tris.Contains(p))
                    pents.Add(p);
            }

            for(long i = 1; i <= max; i++)
            {
                var h = 2*i*i - i;
                if (pents.Contains(h))
                    hexs.Add(h);
            }
            
            return new { result = hexs };
        }
        
        
    }    
}
